// User
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';

export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';

export const ERROR_GOOGLE_LOGIN = 'ERROR_GOOGLE_LOGIN';
export const REQUEST_GOOGLE_LOGIN = 'REQUEST_GOOGLE_LOGIN';
export const SUCCESS_GOOGLE_LOGIN = 'SUCCESS_GOOGLE_LOGIN';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';

// Orders List
export const REQUEST_ORDERS_LIST = 'REQUEST_ORDERS_LIST';
export const RECEIVE_ORDERS_LIST = 'RECEIVE_ORDERS_LIST';
export const ERROR_ORDERS_LIST = 'ERROR_ORDERS_LIST';

// Delete Order
export const REQUEST_DELETE_ORDER = 'REQUEST_DELETE_ORDER';
export const SUCCESS_DELETE_ORDER = 'SUCCESS_DELETE_ORDER';
export const ERROR_DELETE_ORDER = 'ERROR_DELETE_ORDER';
export const CLEAR_DELETE_ERROR = 'CLEAR_DELETE_ERROR';

// Pagination & Filters
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_PAGE_SIZE = 'SET_PAGE_SIZE';
export const SET_FILTERS = 'SET_FILTERS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';

// Order Details
export const REQUEST_ORDER_DETAILS = 'REQUEST_ORDER_DETAILS';
export const RECEIVE_ORDER_DETAILS = 'RECEIVE_ORDER_DETAILS';
export const ERROR_ORDER_DETAILS = 'ERROR_ORDER_DETAILS';

// Update Order
export const REQUEST_UPDATE_ORDER = 'REQUEST_UPDATE_ORDER';
export const SUCCESS_UPDATE_ORDER = 'SUCCESS_UPDATE_ORDER';
export const ERROR_UPDATE_ORDER = 'ERROR_UPDATE_ORDER';

// Create Order
export const REQUEST_CREATE_ORDER = 'REQUEST_CREATE_ORDER';
export const SUCCESS_CREATE_ORDER = 'SUCCESS_CREATE_ORDER';
export const ERROR_CREATE_ORDER = 'ERROR_CREATE_ORDER';

// SNACKBAR
export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const CLEAR_SNACKBAR = 'CLEAR_SNACKBAR';
